version: '3'
services:
    localstack:
      image: localstack/localstack
      ports:
        - 4567-4578:4567-4578
        - 8080:8080

    local:
        build:
            context: .
            dockerfile: Dockerfile_Local
        working_dir: /root/dev
        volumes:
            - ../:/root/dev
            - ./config/.aws/config:/root/.aws/config
            - ./config/.aws/credentials:/root/.aws/credentials
            - /var/run/docker.sock:/var/run/docker.sock # sam local required docker todo: docker in docker
        environment:
          - APPLICATION=$PWD/../application # ホスト側のdockerを使用しているため、localコンテナのディレクトリではなく、ホスト側のディレクトリがmountされる
        ports:
            - 3000:3000
        depends_on:
            - localstack
        command: ./container/shell/local.sh

    go:
        build:
            context: .
            dockerfile: Dockerfile_go
        working_dir: /go/src/DummyJsonGenerator/application
        volumes:
            - ../:/go/src/DummyJsonGenerator/
        command: bash /go/src/DummyJsonGenerator/container/shell/go.sh
