AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  Register:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Register
      Handler: registerHandler
      Runtime: go1.x
      AutoPublishAlias: live
      Timeout: 10
      MemorySize: 128
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  WatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Register}
      RetentionInDays: 1
